### ISSUE TITLE
Fix API post-refactor

### ISSUE THREAD

**Issue by crebma** [selfconference/selfconf#12]

**Comment by macklinu** [comment]
Let's sync up on an API for the mobile apps to consume. I would be down to help get an API v2 doc going, because I think we could reduce a lot of the data sent to the mobile clients. (I'm not sure this applies to the Rails app, but maybe it does? I think you'd know more about if any API changes would help/hurt the Rails app.)

**Comment by crebma** [comment]
fixed ages ago
